### ISSUE TITLE
stdout maxBuffer exceeded on bootstrap

### ISSUE THREAD

**Issue by rygine** [asini/asini#10]
when using `ChildProcessUtilities.exec`, the `maxBuffer` can be exceeded during bootstrap.

increasing `maxBuffer` to `500*1024` should do the trick. (500KB) seems reasonable.

**Comment by gigabo** [comment]
This is during `prepublish` (from discussion on slack).

Should also emit captured `stdout` output on error.

Good issue @rygine.

**Comment by gigabo** [comment]
Logging stdout output tracked separately in #11.
