### ISSUE TITLE
Automatic hoisting of common dependencies

### ISSUE THREAD

**Issue by rygine** [asini/asini#14]
creating this issue to track discussion of implementation.

this feature will:
- find common dependencies amongst all packages
  *\* subject to semver compatibility
  *\* incompatible (less common) versions of the same common dependency will be installed normally within each package
- check for collisions with existing dependencies at the repo root
  *\* figure out how to handle this situation
- install common dependencies at repo root

some thoughts.
- should this only work with `peerDependencies` by default, with an option to hoist everything?
- this could create a scenario where a package's dependencies are stale because a required dependency has been hoisted. should we include a health check to make sure all dependencies are defined?

**Comment by gigabo** [comment]
> incompatible (less common) versions of the same common dependency will be installed normally within each package

This should trigger a _warning_.

> check for collisions with existing dependencies at the repo root *\* figure out how to handle this situation

This should be an _error_ if semver incompatible.  Otherwise, a noop.

> should this only work with peerDependencies by default

I think [the case has been made](https://github.com/lerna/lerna/pull/318) pretty convincingly that we shouldn't install `peerDependencies` at all, actually.

Strategies that seem reasonable:
- Hoist _all_ external deps, and support opt-out on a per-dep basis (e.g. `--no-hoist=lodash`).
- Hoist _nothing_ by default and support opt-in (e.g. `--hoist=babel*`).
- Support _both_ opt-in and opt-out (e.g. `--hoist=* --no-hoist=lodash`).

**Comment by gigabo** [comment]
Thanks for taking this on @rygine!

**Comment by rygine** [comment]
> I think the case has been made pretty convincingly that we shouldn't install peerDependencies at all, actually.

if my mono repo is all `react` components, and `react` is in `peerDependencies` of all packages, wouldn't it make sense to hoist it? this is definitely confusing to me as i'll want a live demo/test running during development. is `react` part of `devDependencies` and `peerDependencies`? i've never been able to find clarity on this.

> Strategies that seem reasonable:
> - Hoist all external deps, and support opt-out on a per-dep basis (e.g. --no-hoist=lodash).
> - Hoist nothing by default and support opt-in (e.g. --hoist=babel*).
> - Support both opt-in and opt-out (e.g. --hoist=\* --no-hoist=lodash).

what about making hoisting optional by default. `--hoist` will hoist everything intelligently. `--hoist=babel*` will only hoist specific packages, and `--no-hoist=lodash` will exclude certain packages from being hoisted.

i don't think `meow`/`minimist` care about argument types so it should support boolean/string for the `--hoist` option.

**Comment by gigabo** [comment]
> is react part of `devDependencies` and `peerDependencies`?

Yeah, AFAIK that's the only sane way to handle it in npm3.

> `--hoist` will hoist everything intelligently. `--hoist=babel*` will hoist specific packages, and `--no-hoist=lodash` will exclude certain packages from being hoisted.

Awesome! :metal:

**Comment by gigabo** [comment]
Oh... actually I wonder if the option name should be `--hoist-external`.  Not quite as nice to look at (or type), but a little more clear that it only applies to external dependencies. 😕

**Comment by rygine** [comment]
i think it may be implied. internal/local packages are just symlinked to each other. or maybe the docs need an update. ;)

**Comment by rygine** [comment]
@gigabo closing this as it's merged! :)
