### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ntharim** [asini/asini#77]
HI @gigabo could you please publish the new version with `asini add` to npm?

**Comment by gigabo** [comment]
@nthtran You bet!  Published [`v1.4.0`](https://github.com/asini/asini/releases/tag/v1.4.0).  This will probably be the last version of Asini, though.  Moving development back to Lerna.  If all goes well we'll be able to stay there this time. 🤞 

Thanks for your support!

**Comment by ntharim** [comment]
Thank you for for all your hard work!
